# Generated by Django 3.0.7 on 2020-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='use_me_as_profile',
            field=models.BooleanField(default=False),
        ),
    ]
